
-- Generated by ORDS REST Data Services 24.3.2.r3121009
-- Schema: DEMO  Date: Wed Feb 19 12:32:59 2025 
--
        
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'DEMO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'demo',
      p_auto_rest_auth      => TRUE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'cms_oci',
      p_base_path      => '/cms_oci/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'cms_oci',
      p_pattern        => 'recebimento',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'cms_oci',
      p_pattern        => 'recebimento',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => 'Procedimento para listagem de arquivos',
      p_source         => 
'SELECT 
    c.object_name,
    ROUND(c.bytes/1024/1024, 2) as "Tamanho (MB)",
    l.status_processamento as "Status Processamento",
    l.data_upload as "Data Upload",
    l.data_processamento as "Data Processamento",
    l.quem_fez_upload as "Quem fez o upload",
    ''Download'' as download_object,
    ''Delete'' as delete_object
FROM 
    dbms_cloud.list_objects(''CREDENCIALOS'','''' || :object_storage_url || '''') c, controle_upload l
where c.object_name = l.nome_arquivo
order by l.data_upload');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'cms_oci',
      p_pattern            => 'recebimento',
      p_method             => 'GET',
      p_name               => 'object_storage_url',
      p_bind_variable_name => 'object_storage_url',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'cms_oci',
      p_pattern            => 'recebimento',
      p_method             => 'GET',
      p_name               => 'X-APEX-FORWARD',
      p_bind_variable_name => 'location',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'cms_oci',
      p_pattern            => 'recebimento',
      p_method             => 'GET',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'cms_oci',
      p_pattern        => 'recebimento/:file_name',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'cms_oci',
      p_pattern        => 'recebimento/:file_name',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => 'Deletar arquivo',
      p_source         => 
'begin
    dbms_cloud.delete_object(
        credential_name => ''CREDENCIALOS'',
        object_uri      => :object_storage_url || :file_name);

update 
    CONTROLE_UPLOAD
set 
    DATA_DELETOUARQUIVO = CURRENT_TIMESTAMP,
    QUEM_DELETOUARQUIVO = ''CAIO OLIVEIRA''
WHERE
    NOME_ARQUIVO = :file_name;
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'cms_oci',
      p_pattern            => 'recebimento/:file_name',
      p_method             => 'DELETE',
      p_name               => 'X-APEX-FORWARD',
      p_bind_variable_name => 'location',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'cms_oci',
      p_pattern            => 'recebimento/:file_name',
      p_method             => 'DELETE',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'cms_oci',
      p_pattern            => 'recebimento/:file_name',
      p_method             => 'DELETE',
      p_name               => 'object_storage_url',
      p_bind_variable_name => 'object_storage_url',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'cms_oci',
      p_pattern            => 'recebimento/:file_name',
      p_method             => 'DELETE',
      p_name               => 'file_name',
      p_bind_variable_name => 'fila_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'cms_oci',
      p_pattern        => 'recebimento/:file_name',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => 'download',
      p_source         => 
'declare
  l_file blob;
  l_mime_type varchar2(32767);
begin

  l_file := dbms_cloud.get_object(
    credential_name => ''CREDENCIALOS'',
    object_uri      => :object_storage_url || :file_name);

  l_mime_type := ''application/octet-stream'';

  sys.htp.init;
  sys.owa_util.mime_header(l_mime_type, false);
  sys.htp.p(''content-length: '' || dbms_lob.getlength(l_file));
  sys.htp.p(''content-disposition: filename="'' || :file_name || ''"'');
  sys.owa_util.http_header_close;
  sys.wpg_docload.download_file(l_file);

--  apex_application.stop_apex_engine;

end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'cms_oci',
      p_pattern            => 'recebimento/:file_name',
      p_method             => 'GET',
      p_name               => 'file_name',
      p_bind_variable_name => 'file_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'cms_oci',
      p_pattern            => 'recebimento/:file_name',
      p_method             => 'GET',
      p_name               => 'X-APEX-FORWARD',
      p_bind_variable_name => 'location',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'cms_oci',
      p_pattern            => 'recebimento/:file_name',
      p_method             => 'GET',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'cms_oci',
      p_pattern            => 'recebimento/:file_name',
      p_method             => 'GET',
      p_name               => 'object_storage_url',
      p_bind_variable_name => 'object_storage_url',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'cms_oci',
      p_pattern        => 'recebimento/:file_name',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'text/csv',
      p_comments       => NULL,
      p_source         => 
'DECLARE 
   -- Variables
   v_bucket_name      VARCHAR2(300);
   v_file_name        VARCHAR2(300);
   v_tempid           VARCHAR2(50);
   v_tempdate         DATE;
   v_uniqname         VARCHAR2(600);
   v_blob_content     BLOB;
   v_file_size        NUMBER;
   v_object_uri       VARCHAR2(1000);
   v_column_count     NUMBER;
   v_row_count        NUMBER;
   v_header_mismatch  NUMBER;
   v_extensao         varchar2(200);

BEGIN
--   v_bucket_name := :bucket_name;
   v_file_name := :file_name;
   v_tempid := TO_CHAR(SYSTIMESTAMP, ''YYYYMMDDHH24MISSFF3''); 
   v_tempdate := SYSDATE;
   v_uniqname := v_tempid || ''_'' || v_file_name;
   v_object_uri := :object_storage_url || v_uniqname;
   v_extensao := :extensao;

   -- Insert blob data into APICALLAUX
   INSERT INTO APICALLAUX (
       application_id,
       name,
       filename,
       mime_type,
       created_on,
       blob_content
   ) VALUES (
       v_tempid,   -- Ensure this matches the column data ty' || 'pe
       v_uniqname, 
       v_file_name,
       v_extensao,
       v_tempdate,
       :BODY
   ) RETURNING blob_content INTO v_blob_content;

   -- VALIDATION: Check column count (must be 12)
   SELECT COUNT(*) INTO v_column_count
   FROM (
       SELECT REPLACE(column_name, '']'', ''_'') AS modified_column_name
       FROM TABLE(APEX_DATA_PARSER.GET_COLUMNS(
           APEX_DATA_PARSER.DISCOVER(
               p_content   => v_blob_content,
               p_file_name => v_uniqname,
               p_max_rows  => 10
           )
       ))
   );

   -- VALIDATION: Check row count (must be > 0)
   SELECT JSON_VALUE(profile_json, ''$."parsed-rows"'' RETURNING NUMBER) - 1 
   INTO v_row_count
   FROM (
       SELECT APEX_DATA_PARSER.DISCOVER(
           p_content   => v_blob_content,
           p_file_name => v_uniqname,
           p_max_rows  => 10
       ) AS profile_json
   );

   -- VALIDATION: Check header names
   SELECT COUNT(*) INTO v_header_mismatch
  ' || ' FROM (
       -- Required column names
       SELECT column_value AS column_name 
       FROM TABLE(SYS.ODCIVARCHAR2LIST(
           ''CPF'', ''NOME_COMPLETO'', ''RUA'', ''NUMERO'', ''COMPLEMENTO'', 
           ''CIDADE'', ''ESTADO'', ''PREPOSICAO'', ''DATA_ATUALIZACAO'', 
           ''CEP'', ''TELEFONE'', ''EMAIL''
       ))
       MINUS
       -- Extracted column names from file
       SELECT REPLACE(column_name, '']'', ''_'') AS column_name
       FROM TABLE(APEX_DATA_PARSER.GET_COLUMNS(
           APEX_DATA_PARSER.DISCOVER(
               p_content   => v_blob_content,
               p_file_name => v_uniqname,
               p_max_rows  => 10
           )
       ))
   );

   -- Validation checks
   IF 
      --v_bucket_name IS NULL OR 
      v_file_name IS NULL 
      OR v_column_count <> 12
      OR v_row_count = 0
      OR v_header_mismatch > 0
   THEN
   sys.htp.p(sys.htf.escape_sc(''Erro ao processar arquivo: Corrija os problemas com o template e tente novamente'')); 
   sys.ht' || 'p.p(sys.htf.escape_sc(''O arquivo precisa ter 12 colunas, possui: '' || v_column_count));
   sys.htp.p(sys.htf.escape_sc(''O arquivo não deve estar vazio (se 0 esta vazio, se 1 contém linhas): '' || v_row_count));
   sys.htp.p(sys.htf.escape_sc(''O arquivo precisa ter as mesmas colunas do template. Qtde colunas com erro: '' || v_header_mismatch));

    DELETE FROM APICALLAUX WHERE NAME = v_uniqname;
    COMMIT;
    RETURN; -- Stop execution
   END IF;

   -- Get file size
   v_file_size := DBMS_LOB.GETLENGTH(v_blob_content);

   -- Upload data to Object Storage
   DBMS_CLOUD.PUT_OBJECT (
      credential_name => ''CREDENCIALOS'',
      object_uri      => v_object_uri,
      contents        => v_blob_content
   );

   -- Insert into controle_upload
   INSERT INTO controle_upload (
       nome_arquivo, 
       url_os, 
       status_processamento, 
       tamanho_arquivo, 
       data_upload, 
       quem_fez_upload
   ) VALUES (
       v_uniqname, 
       v_object_u' || 'ri, 
       ''Enviado'', 
       v_file_size, 
       SYSTIMESTAMP, 
       ''CAIO OLIVEIRA''
   );

   -- Final cleanup
   DELETE FROM APICALLAUX WHERE NAME = v_uniqname;
   COMMIT;

   sys.htp.p(sys.htf.escape_sc(''Arquivo processado com sucesso'')); 
END;
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'cms_oci',
      p_pattern            => 'recebimento/:file_name',
      p_method             => 'POST',
      p_name               => 'Content-Type',
      p_bind_variable_name => 'extensao',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'cms_oci',
      p_pattern            => 'recebimento/:file_name',
      p_method             => 'POST',
      p_name               => 'object_storage_url',
      p_bind_variable_name => 'object_storage_url',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'cms_oci',
      p_pattern            => 'recebimento/:file_name',
      p_method             => 'POST',
      p_name               => 'file_name',
      p_bind_variable_name => 'file_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

    
  ORDS.CREATE_ROLE(p_role_name => 'cms_oci');
    
  l_roles(1) := 'cms_oci';
  l_modules(1) := 'cms_oci';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'cms_oci',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'cms_oci',
      p_description    => NULL,
      p_comments       => NULL);

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;
        
COMMIT;

END;